### ISSUE TITLE
parser extracts 2 minutes from "2 month" even if specific time is supplied

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#330] opened 2017-04-18 17:15 UTC
"1:30-2:45pm 2 month planning meeting" resolved to "0h 2m"

**Comment by chrisfosterelli** [comment] 2017-04-18 17:55
Is this a duplicate of #319? The "2 m" looks like the same bug.

**Comment by jonotron** [comment] 2017-04-18 18:22
I believe it is a duplicate. Thanks for the find.

**Closed** 2017-04-18 18:23 UTC
Labels: bug, duplicate, parser mistake
